{
 "title": "Cynet / Alerts-storage-converter",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Service metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Alert2Storage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(service_timing_count{service=\"alerts-storage-converter\"}[1m])) by (client, key)",
     "legendFormat": " {{client}} - {{key}}"
    }
   ]
  },
  {
   "title": "Event timing",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(service_timing_sum{service=\"alerts-storage-converter\"}/service_timing_count{service=\"alerts-storage-converter\"}) by (client, key)",
     "legendFormat": "{{client}} {{key}}"
    }
   ]
  },
  {
   "title": "API errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(service_error_counter{service=\"alerts-storage-converter\"}[1m])) by (client, key)",
     "legendFormat": "{{client}} - {{key}}"
    }
   ]
  },
  {
   "title": "Response duration",
   "type": "heatmap",
   "description": "Response duration (ms)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(service_timing_bucket{service=\"alerts-storage-converter\"}[30m])) by (le)",
     "legendFormat": "{{le}} ms"
    }
   ]
  },
  {
   "title": "golang metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of goroutines that currently exist",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_goroutines{service=\"alerts-storage-converter\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Uptime (second)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 9, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(runtime_uptime{service=\"alerts-storage-converter\"}) by (pod) / 1000",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of live objects is the number of cumulative Mallocs - Frees",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_mem_live_objects{service=\"alerts-storage-converter\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "MB of allocated heap objects",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_mem_heap_alloc{service=\"alerts-storage-converter\"}) by (pod) / 1048576",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of allocated heap objects",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_mem_heap_objects{service=\"alerts-storage-converter\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "MB in in-use spans",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_mem_heap_inuse{service=\"alerts-storage-converter\"}) by (pod) / 1048576",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "MB of heap memory obtained from the OS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_mem_heap_sys{service=\"alerts-storage-converter\"}) by (pod) / 1048576",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "MB of idle spans whose physical memory has been returned to the OS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_mem_heap_released{service=\"alerts-storage-converter\"}) by (pod) / 1048576",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "MB in idle (unused) spans",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_mem_heap_idle{service=\"alerts-storage-converter\"}) by (pod) / 1048576",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of completed garbage collection cycles",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_gc_count{service=\"alerts-storage-converter\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Cumulative nanoseconds in GC stop-the-world pauses since the program started",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_gc_pause_total_ns{service=\"alerts-storage-converter\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of pointer lookups performed by the runtime",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_mem_lookups{service=\"alerts-storage-converter\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of cgo calls made by the current process",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_runtime_go_cgo_calls{service=\"alerts-storage-converter\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}