{
 "title": "Cynet / Custom-remediations service",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Api metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "API requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(api_timing_count{service=\"custom-remediations\"}[1m])) by (client, url_tpl, http_code)",
     "legendFormat": "{{client}} - {{url_tpl}} - {{http_code}}"
    }
   ]
  },
  {
   "title": "API errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(api_error_counter{service=\"custom-remediations\"}[1m])) by (client, key, code)",
     "legendFormat": "{{client}} - {{key}} - {{code}}"
    }
   ]
  },
  {
   "title": "Response duration",
   "type": "heatmap",
   "description": "Response duration (ms)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(api_timing_bucket{service=\"custom-remediations\"}[30m])) by (le)",
     "legendFormat": "{{le}} ms"
    }
   ]
  },
  {
   "title": "API timing",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(api_timing_sum{service=\"custom-remediations\"}/api_timing_count{service=\"custom-remediations\"}) by (client, method, url_tpl)",
     "legendFormat": "{{client}} {{method}} {{url_tpl}}"
    }
   ]
  },
  { "title": "service metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Service errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(service_error_counter{service=\"custom-remediations\"}[1m])) by (client, key)",
     "legendFormat": "{{client}} - {{key}}"
    }
   ]
  },
  { "title": "golang metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Number of goroutines that currently exist",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(process_runtime_go_goroutines{service=\"custom-remediations\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Uptime (second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(runtime_uptime{service=\"custom-remediations\"}) by (pod) / 1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of live objects is the number of cumulative Mallocs - Frees",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(process_runtime_go_mem_live_objects{service=\"custom-remediations\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "MB of allocated heap objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(process_runtime_go_mem_heap_alloc{service=\"custom-remediations\"}) by (pod) / 1048576",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of allocated heap objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(process_runtime_go_mem_heap_objects{service=\"custom-remediations\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "MB in in-use spans",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(process_runtime_go_mem_heap_inuse{service=\"custom-remediations\"}) by (pod) / 1048576",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "MB of heap memory obtained from the OS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(process_runtime_go_mem_heap_sys{service=\"custom-remediations\"}) by (pod) / 1048576",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "MB of idle spans whose physical memory has been returned to the OS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(process_runtime_go_mem_heap_released{service=\"custom-remediations\"}) by (pod) / 1048576",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "MB in idle (unused) spans",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(process_runtime_go_mem_heap_idle{service=\"custom-remediations\"}) by (pod) / 1048576",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of completed garbage collection cycles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(process_runtime_go_gc_count{service=\"custom-remediations\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Cumulative nanoseconds in GC stop-the-world pauses since the program started",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(process_runtime_go_gc_pause_total_ns{service=\"custom-remediations\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of pointer lookups performed by the runtime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(process_runtime_go_mem_lookups{service=\"custom-remediations\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of cgo calls made by the current process",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_runtime_go_cgo_calls{service=\"custom-remediations\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}