{
 "title": "Cynet / customer-info",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Api metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(api_timing_count{service=\"customer-info\"}[1m])) by (url_tpl, http_code)",
     "legendFormat": "{{url_tpl}} - {{http_code}}"
    }
   ]
  },
  {
   "title": "API errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(api_error_counter{service=\"customer-info\"}[1m])) by (client, key, code)",
     "legendFormat": "{{client}} - {{key}} - {{code}}"
    }
   ]
  },
  {
   "title": "API timing",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(api_timing_sum{service=\"customer-info\"}[1m])) by (method, url_tpl)",
     "legendFormat": "{{method}} {{url_tpl}}"
    }
   ]
  },
  {
   "title": "service metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service timing",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(service_timing_sum{service=\"customer-info\"}[1m])) by (key)",
       "legendFormat": "{{key}}"
      }
     ]
    },
    {
     "title": "Service record",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(service_record_sum{service=\"customer-info\"}[1m])) by (key)",
       "legendFormat": "{{key}}"
      }
     ]
    },
    {
     "title": "Service errors",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(service_error_counter{service=\"customer-info\"}[1m])) by (client, key)",
       "legendFormat": "{{client}} - {{key}}"
      }
     ]
    }
   ]
  },
  {
   "title": "golang metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of goroutines that currently exist",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_goroutines{service=\"customer-info\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Uptime (second)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 9, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(runtime_uptime{service=\"customer-info\"}) by (pod) / 1000",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of live objects is the number of cumulative Mallocs - Frees",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_mem_live_objects{service=\"customer-info\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "MB of allocated heap objects",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_mem_heap_alloc{service=\"customer-info\"}) by (pod) / 1048576",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of allocated heap objects",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_mem_heap_objects{service=\"customer-info\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "MB in in-use spans",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_mem_heap_inuse{service=\"customer-info\"}) by (pod) / 1048576",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "MB of heap memory obtained from the OS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_mem_heap_sys{service=\"customer-info\"}) by (pod) / 1048576",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "MB of idle spans whose physical memory has been returned to the OS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_mem_heap_released{service=\"customer-info\"}) by (pod) / 1048576",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "MB in idle (unused) spans",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_mem_heap_idle{service=\"customer-info\"}) by (pod) / 1048576",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of completed garbage collection cycles",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_gc_count{service=\"customer-info\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Cumulative nanoseconds in GC stop-the-world pauses since the program started",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_gc_pause_total_ns{service=\"customer-info\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of pointer lookups performed by the runtime",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_mem_lookups{service=\"customer-info\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of cgo calls made by the current process",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_runtime_go_cgo_calls{service=\"customer-info\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}