{
 "title": "Cynet / Files-info service",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "api metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(api_timing_count{service=\"files-info\"}[1m])) by (tenant, url_tpl, http_code)",
     "legendFormat": "{{tenant}}{{url_tpl}} {{http_code}}"
    }
   ]
  },
  {
   "title": "API timing",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(api_timing_sum{service=\"files-info\"}/api_timing_count{service=\"files-info\"}) by (method, url_tpl)",
     "legendFormat": "{{tenant}}{{method}} {{url_tpl}}"
    }
   ]
  },
  {
   "title": "API errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(api_error_counter{service=\"files-info\"}[1m])) by (tenant, key, code)",
     "legendFormat": "{{tenant}}{{key}} {{code}}"
    }
   ]
  },
  {
   "title": "API timing",
   "type": "heatmap",
   "description": "API timing (ms)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(api_timing_bucket{service=\"files-info\"}[10m])) by (le)",
     "legendFormat": "{{le}} ms"
    }
   ]
  },
  {
   "title": "service metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(service_error_counter{service=\"files-info\"}[1m])) by (tenant,  key)",
       "legendFormat": "{{tenant}}{{key}}"
      }
     ]
    }
   ]
  },
  {
   "title": "golang metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of cgo calls made by the current process",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_runtime_go_cgo_calls{service=\"files-info\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of pointer lookups performed by the runtime",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_mem_lookups{service=\"files-info\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "MB of allocated heap objects",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_mem_heap_alloc{service=\"files-info\"}) by (pod) / 1048576",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Cumulative nanoseconds in GC stop-the-world pauses since the program started",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_gc_pause_total_ns{service=\"files-info\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of completed garbage collection cycles",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_gc_count{service=\"files-info\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of allocated heap objects",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_mem_heap_objects{service=\"files-info\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "MB in idle (unused) spans",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_mem_heap_idle{service=\"files-info\"}) by (pod) / 1048576",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of live objects is the number of cumulative Mallocs - Frees",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_mem_live_objects{service=\"files-info\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "MB of idle spans whose physical memory has been returned to the OS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_mem_heap_released{service=\"files-info\"}) by (pod) / 1048576",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "MB in in-use spans",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_mem_heap_inuse{service=\"files-info\"}) by (pod) / 1048576",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of goroutines that currently exist",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_goroutines{service=\"files-info\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Uptime (second)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(runtime_uptime{service=\"files-info\"}) by (pod) / 1000",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Panel TitleMB of heap memory obtained from the OS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 14, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_mem_heap_sys{service=\"files-info\"}) by (pod) / 1048576",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}