{
 "title": "Cynet / Notifications-management service",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "api metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "API requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(api_timing_count{service=\"notifications-management\"}[1m])) by (tenant, client, url_tpl, http_code)",
       "legendFormat": "{{tenant}} {{client}} {{url_tpl}} {{http_code}}"
      }
     ]
    },
    {
     "title": "API timing",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(api_timing_sum{service=\"notifications-management\"}/api_timing_count{service=\"notifications-management\"}) by (client, method, url_tpl)",
       "legendFormat": "{{tenant}} {{client}} {{method}} {{url_tpl}}"
      }
     ]
    },
    {
     "title": "API errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(api_error_counter{service=\"notifications-management\"}[1m])) by (tenant, client, key, code)",
       "legendFormat": "{{tenant}} {{client}} {{key}} {{code}}"
      }
     ]
    },
    {
     "title": "API timing",
     "type": "heatmap",
     "description": "API timing (ms)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "sum(increase(api_timing_bucket{service=\"notifications-management\"}[10m])) by (le)",
       "legendFormat": "{{le}} ms"
      }
     ]
    }
   ]
  },
  {
   "title": "service metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(service_error_counter{service=\"notifications-management\"}[1m])) by (tenant, client, key)",
       "legendFormat": "{{tenant}} {{client}} {{key}}"
      }
     ]
    }
   ]
  },
  {
   "title": "golang metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of cgo calls made by the current process",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_runtime_go_cgo_calls{service=\"notifications-management\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of pointer lookups performed by the runtime",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_mem_lookups{service=\"notifications-management\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "MB of allocated heap objects",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_mem_heap_alloc{service=\"notifications-management\"}) by (pod) / 1048576",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Cumulative nanoseconds in GC stop-the-world pauses since the program started",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_gc_pause_total_ns{service=\"notifications-management\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of completed garbage collection cycles",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_gc_count{service=\"notifications-management\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of allocated heap objects",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_mem_heap_objects{service=\"notifications-management\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "MB in idle (unused) spans",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_mem_heap_idle{service=\"notifications-management\"}) by (pod) / 1048576",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of live objects is the number of cumulative Mallocs - Frees",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_mem_live_objects{service=\"notifications-management\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "MB of idle spans whose physical memory has been returned to the OS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_mem_heap_released{service=\"notifications-management\"}) by (pod) / 1048576",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "MB in in-use spans",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_mem_heap_inuse{service=\"notifications-management\"}) by (pod) / 1048576",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of goroutines that currently exist",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_goroutines{service=\"notifications-management\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Uptime (second)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(runtime_uptime{service=\"notifications-management\"}) by (pod) / 1000",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Panel TitleMB of heap memory obtained from the OS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 14, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_runtime_go_mem_heap_sys{service=\"notifications-management\"}) by (pod) / 1048576",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}