{
 "title": "RDS resource monitor - US",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "production-mariadb-us-east-1-0",
     "dimensions": { "DBInstanceIdentifier": "ninjas-mariadb-us-east-1-0" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    },
    {
     "alias": "production-mariadb-us-east-1-1",
     "dimensions": { "DBInstanceIdentifier": "production-mariadb-us-east-1-1" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    },
    {
     "alias": "production-mariadb-us-east-1-2",
     "dimensions": { "DBInstanceIdentifier": "production-mariadb-us-east-1-2" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    },
    {
     "alias": "production-mariadb-us-east-1-3",
     "dimensions": { "DBInstanceIdentifier": "production-mariadb-us-east-1-3" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    },
    {
     "alias": "production-mariadb-us-east-1-4",
     "dimensions": { "DBInstanceIdentifier": "production-mariadb-us-east-1-4" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "alias": "production-mariadb-us-east-1-0",
     "dimensions": { "DBInstanceIdentifier": "production-mariadb-us-east-1-0" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    },
    {
     "alias": "production-mariadb-us-east-1-1",
     "dimensions": { "DBInstanceIdentifier": "production-mariadb-us-east-1-1" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    },
    {
     "alias": "production-mariadb-us-east-1-2",
     "dimensions": { "DBInstanceIdentifier": "production-mariadb-us-east-1-2" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    },
    {
     "alias": "production-mariadb-us-east-1-3",
     "dimensions": { "DBInstanceIdentifier": "production-mariadb-us-east-1-3" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    },
    {
     "alias": "production-mariadb-us-east-1-4",
     "dimensions": { "DBInstanceIdentifier": "production-mariadb-us-east-1-4" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Read Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "alias": "production-mariadb-us-east-1-0",
     "dimensions": { "DBInstanceIdentifier": "production-mariadb-us-east-1-0" },
     "metricName": "ReadLatency",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    },
    {
     "alias": "production-mariadb-us-east-1-1",
     "dimensions": { "DBInstanceIdentifier": "production-mariadb-us-east-1-1" },
     "metricName": "ReadLatency",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    },
    {
     "alias": "production-mariadb-us-east-1-2",
     "dimensions": { "DBInstanceIdentifier": "production-mariadb-us-east-1-2" },
     "metricName": "ReadLatency",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    },
    {
     "alias": "production-mariadb-us-east-1-3",
     "dimensions": { "DBInstanceIdentifier": "production-mariadb-us-east-1-3" },
     "metricName": "ReadLatency",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    },
    {
     "alias": "production-mariadb-us-east-1-4",
     "dimensions": { "DBInstanceIdentifier": "production-mariadb-us-east-1-4" },
     "metricName": "ReadLatency",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "alias": "production-mariadb-us-east-1-0",
     "dimensions": { "DBInstanceIdentifier": "production-mariadb-us-east-1-0" },
     "metricName": "WriteLatency",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    },
    {
     "alias": "production-mariadb-us-east-1-1",
     "dimensions": { "DBInstanceIdentifier": "production-mariadb-us-east-1-1" },
     "metricName": "WriteLatency",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    },
    {
     "alias": "production-mariadb-us-east-1-2",
     "dimensions": { "DBInstanceIdentifier": "production-mariadb-us-east-1-2" },
     "metricName": "WriteLatency",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    },
    {
     "alias": "production-mariadb-us-east-1-3",
     "dimensions": { "DBInstanceIdentifier": "production-mariadb-us-east-1-3" },
     "metricName": "WriteLatency",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    },
    {
     "alias": "production-mariadb-us-east-1-4",
     "dimensions": { "DBInstanceIdentifier": "production-mariadb-us-east-1-4" },
     "metricName": "WriteLatency",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Number of Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "alias": "production-mariadb-us-east-1-0",
     "dimensions": { "DBInstanceIdentifier": "production-mariadb-us-east-1-0" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    },
    {
     "alias": "production-mariadb-us-east-1-1",
     "dimensions": { "DBInstanceIdentifier": "production-mariadb-us-east-1-1" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    },
    {
     "alias": "production-mariadb-us-east-1-2",
     "dimensions": { "DBInstanceIdentifier": "production-mariadb-us-east-1-2" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    },
    {
     "alias": "production-mariadb-us-east-1-3",
     "dimensions": { "DBInstanceIdentifier": "production-mariadb-us-east-1-3" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    },
    {
     "alias": "production-mariadb-us-east-1-4",
     "dimensions": { "DBInstanceIdentifier": "production-mariadb-us-east-1-4" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "alias": "production-mariadb-us-east-1-0",
     "dimensions": { "DBInstanceIdentifier": "production-mariadb-us-east-1-0" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    },
    {
     "alias": "production-mariadb-us-east-1-1",
     "dimensions": { "DBInstanceIdentifier": "production-mariadb-us-east-1-1" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    },
    {
     "alias": "production-mariadb-us-east-1-2",
     "dimensions": { "DBInstanceIdentifier": "production-mariadb-us-east-1-2" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    },
    {
     "alias": "production-mariadb-us-east-1-3",
     "dimensions": { "DBInstanceIdentifier": "production-mariadb-us-east-1-3" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    },
    {
     "alias": "production-mariadb-us-east-1-4",
     "dimensions": { "DBInstanceIdentifier": "production-mariadb-us-east-1-4" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    }
   ]
  }
 ]
}