{
 "title": "Cynet / SaaS.Dashboard monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "agentHost",
    "query": "label_values(dashboard_monitoring_agents_health, host_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Host Resources by Global",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(dashboard_global_available_resources{Metric=\"Hosts\"}) by (GlobalName)",
     "legendFormat": "{{GlobalName}}"
    }
   ]
  },
  {
   "title": "Redis Resources by Global",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(dashboard_global_available_resources{Metric=\"Redis Dockers\"}) by (GlobalName)",
     "legendFormat": "{{GlobalName}}"
    }
   ]
  },
  {
   "title": "MySQL Resources by Global",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(dashboard_global_available_resources{Metric=\"MySql Dockers\"}) by (GlobalName)",
     "legendFormat": "{{GlobalName}}"
    }
   ]
  },
  {
   "title": "Global Count by Region",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(dashboard_region_available_resources{Metric=\"Global Count\"}) by (RegionName)",
     "legendFormat": "{{RegionName}}"
    }
   ]
  },
  {
   "title": "Host Resources by Region",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(dashboard_region_available_resources{Metric=\"Hosts\"}) by (RegionName)",
     "legendFormat": "{{RegionName}}"
    }
   ]
  },
  {
   "title": "Registration Pools by Region",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(dashboard_region_available_resources{Metric=\"Registration Pools\"}) by (RegionName)",
     "legendFormat": "{{RegionName}}"
    }
   ]
  },
  {
   "title": "MySQL Resources by Region",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(dashboard_region_available_resources{Metric=\"MySql Dockers\"}) by (RegionName)",
     "legendFormat": "{{RegionName}}"
    }
   ]
  },
  {
   "title": "Redis Resources by Region",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(dashboard_region_available_resources{Metric=\"Redis Dockers\"}) by (RegionName)",
     "legendFormat": "{{RegionName}}"
    }
   ]
  },
  {
   "title": "Host agent actions duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(host_agent_action_duration_seconds_count[5m])) by (action, tenant_id)"
    }
   ]
  },
  {
   "title": "Client PCQ count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dashboard_monitoring_tenants_pcq_count",
     "legendFormat": "{{client_db_id}}"
    }
   ]
  },
  {
   "title": "dashbdashboard_monitoring_tenants_active_scans_dropped",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "dashboard_monitoring_tenants_active_scans_dropped {drop_detected=\"True\"}",
     "legendFormat": "{{client_db_id}}"
    }
   ]
  },
  {
   "title": "Unhealthy dashboard agents",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 38 },
   "repeat": "agentHost",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(dashboard_monitoring_agents_health) by (host_name) == 0",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Inactive count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dashboard_monitoring_to_scans", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Active count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dashboard_monitoring_active_scans",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "DotNet memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes{job=\"dashboard\", namespace=\"cynet\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container Total Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container=\"dashboard\", namespace=\"cynet\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{container=\"dashboard\", namespace=\"cynet\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Blocked Email Messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(notifications_blocked_email_messages[5m])"
    }
   ]
  }
 ]
}