{
 "title": "Cynet / salesforce-data-sync status",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Job Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_job_failed{condition=\"true\",job_name=~\"sales-force-sync-data-sync-daily-.*\", namespace=\"cynet\"}"
    },
    {
     "expr": "kube_job_status_succeeded{job_name=~\"sales-force-sync-data-sync-daily-.*\", namespace=\"cynet\"}"
    }
   ]
  },
  {
   "title": "log monitor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time(({job=\"cynet/sales-force-sync-data-sync-daily\", namespace=\"cynet\"})[$__interval])) by (stream)"
    }
   ]
  },
  {
   "title": "last job salesforce  account sync",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "salesforce_account_update_success_counter{job=\"SFDataSync\"}\n"
    }
   ]
  },
  {
   "title": "number of account that it's receive from salesforce",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "salesforce_get_accounts_counter{job=\"SFDataSync\"}"
    }
   ]
  },
  {
   "title": "last running job update account error ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "salesforce_error_account_update_counter{job=\"SFDataSync\"}"
    }
   ]
  },
  {
   "title": "salesforce account connected with MSSP",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "salesforce_to_mssp_entities{job=\"SFDataSync\"}"
    }
   ]
  },
  {
   "title": "last job  updated MSSPs that sent successfully to rabbit mq",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "salesforce_update_mssps_rabbit_message_sent_success{job=\"SFDataSync\"}"
    }
   ]
  }
 ]
}