{
 "title": "sales-force-account-sync status",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "number of created  MSSPs in dashboard",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Rabbit_MQ_created_new_mssp_entities"
    }
   ]
  },
  {
   "title": "last job - number of new account got from salesforce",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "salesforce_get_accounts_to_create_mssp_counter{job=\"SFNewMsspAccountSync\"}"
    }
   ]
  },
  {
   "title": "last job  - new MSSPs that was error while send to rabbit mq",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "salesforce_update_mssps_rabbit_message_sent_error{job=\"SyncSalesforceAccountToMsspJob\"}"
    }
   ]
  },
  {
   "title": "last job  - new MSSPs that sent successfully to rabbit mq",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "salesforce_update_mssps_rabbit_message_sent_success{job=\"SFNewMsspAccountSync\"}"
    }
   ]
  },
  {
   "title": "Log monitor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time(({job=\"cynet/sales-force-sync-mssp-account-sync-daily\", namespace=\"cynet\"})[$__interval])) by (stream)"
    }
   ]
  },
  {
   "title": "job status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_job_status_succeeded{job_name=~\"sales-force-sync-mssp-account-sync-daily.*\", namespace=\"cynet\"}"
    },
    {
     "expr": "kube_job_failed{condition=\"true\",job_name=~\"sales-force-sync-data-sync-daily.*\", namespace=\"cynet\"}"
    }
   ]
  }
 ]
}