{
 "title": "Cynet / TrafficRouter metrics",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(tr_error_connections,namespace)"
    }
   },
   {
    "name": "deployment",
    "query": {
     "query": "label_values(tr_error_connections,service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cleanup server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "connection_tasks{service=\"$deployment\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}-connections"
    },
    {
     "expr": "rate(connection_auth_failed{service=\"$deployment\", namespace=\"$namespace\"}[5m])",
     "legendFormat": "{{pod}}-auth-failed"
    },
    {
     "expr": "rate(connection_timeout{service=\"$deployment\", namespace=\"$namespace\"}[5m])",
     "legendFormat": "{{pod}}-to"
    },
    {
     "expr": "rate(listener_connection_success{service=\"$deployment\", namespace=\"$namespace\"}[5m])",
     "legendFormat": "{{pod}}-success"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(current_active_connections{service=\"$deployment\", namespace=\"$namespace\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(current_active_connections{service=\"$deployment\", namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Active Connections Delta 1m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(current_active_connections{service=\"$deployment\", namespace=\"$namespace\"}[1m])\r)",
     "legendFormat": "Total"
    },
    {
     "expr": "delta(current_active_connections{service=\"$deployment\", namespace=\"$namespace\"}[1m])\r",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "TCP Requests processing time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg(rate(request_processing_time_bucket{service=\"$deployment\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Request process time"
    },
    {
     "expr": "avg(rate(task_duration_seconds_bucket{service=\"$deployment\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Task duration"
    }
   ]
  },
  {
   "title": "Max active connections",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "current_active_connections{service=\"$deployment\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Active Tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(connection_tasks{service=\"$deployment\", namespace=\"$namespace\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(connection_tasks{service=\"$deployment\", namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "DotNet memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes{job=\"$deployment\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{container=\"traffic-router\", namespace=\"$namespace\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Current active connections",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "current_active_connections{service=\"$deployment\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC collection count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (generation) (increase(dotnet_collection_count_total{namespace=\"$namespace\",job=\"$deployment\"}[5m]))",
     "legendFormat": "Gen{{generation}}"
    }
   ]
  },
  {
   "title": "Container WS Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_namespace_pod_container:container_memory_working_set_bytes{container=\"traffic-router\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container Total Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container=\"traffic-router\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Current active tasks",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "connection_tasks{service=\"$deployment\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Closed connections stats",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(successful_connections{service=\"$deployment\", namespace=\"$namespace\"})",
     "legendFormat": "Successful"
    },
    {
     "expr": "sum(error_connections{service=\"$deployment\", namespace=\"$namespace\"})",
     "legendFormat": "Error"
    },
    {
     "expr": "sum(no_token_connections{service=\"$deployment\", namespace=\"$namespace\"})",
     "legendFormat": "No token"
    },
    {
     "expr": "sum(connection_auth_failed{service=\"$deployment\", namespace=\"$namespace\"})",
     "legendFormat": "Failed Auth"
    },
    {
     "expr": "sum(connection_timeout{service=\"$deployment\", namespace=\"$namespace\"})",
     "legendFormat": "Timed out"
    }
   ]
  }
 ]
}