{
 "title": "Centrifugo",
 "description": "https://centrifugal.dev",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "quantile", "label": "Quantile", "query": "0.5,0.99,0.999" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({__name__=~\"centrifugo_.*\"}, instance)"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "label_values(centrifugo_node_build,  version)"
    }
   },
   { "name": "DS_PROMETHEUS", "query": "Prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Centrifugo $version",
   "type": "text",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "![image](https://centrifugal.github.io/centrifugo/images/favicon.png)"
   }
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(time() - process_start_time_seconds{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Instant connection stats",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(centrifugo_node_num_clients{instance=~\"$instance\"})",
     "legendFormat": "clients"
    },
    {
     "expr": "sum(centrifugo_node_num_users{instance=~\"$instance\"})",
     "legendFormat": "users"
    }
   ]
  },
  {
   "title": "Instant subscription stats",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(centrifugo_node_num_channels{instance=~\"$instance\"})",
     "legendFormat": "channels"
    },
    {
     "expr": "sum(centrifugo_node_num_subscriptions{instance=~\"$instance\"})",
     "legendFormat": "subscriptions"
    }
   ]
  },
  {
   "title": "Num nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(centrifugo_node_num_nodes{instance=~\"$instance\"})",
     "legendFormat": "-"
    }
   ]
  },
  {
   "title": "Client command count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(round(rate(centrifugo_client_command_duration_seconds_count{instance=~\"$instance\"}[$__rate_interval])*60)) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Client command time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(centrifugo_client_command_duration_seconds{quantile=\"$quantile\", instance=~\"$instance\"}) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "API command count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(round(rate(centrifugo_api_command_duration_seconds_count{instance=~\"$instance\"}[$__rate_interval])*60)) by (protocol, method)",
     "legendFormat": "{{protocol}}://{{method}}"
    }
   ]
  },
  {
   "title": "API command time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(centrifugo_api_command_duration_seconds{quantile=\"$quantile\", instance=~\"$instance\"}) by (protocol, method)",
     "legendFormat": "{{protocol}}://{{method}}"
    }
   ]
  },
  {
   "title": "Num client connections per node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "centrifugo_node_num_clients{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Num unique users per node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "centrifugo_node_num_users{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Num unique channels per node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "centrifugo_node_num_channels{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of subscriptions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 20 },
   "targets": [
    {
     "expr": "centrifugo_node_num_subscriptions{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node messages sent count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(round(rate(centrifugo_node_messages_sent_count{instance=~\"$instance\"}[$__rate_interval])*60)) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Node messages received count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(centrifugo_node_messages_received_count{instance=~\"$instance\"}[$__rate_interval])*60) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Transport total messages sent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(centrifugo_transport_messages_sent{instance=~\"$instance\"}[$__rate_interval])*60) by (transport)",
     "legendFormat": "{{transport}}"
    }
   ]
  },
  {
   "title": "Transport connection rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(round(rate(centrifugo_transport_connect_count{instance=~\"$instance\"}[$__rate_interval])*60)) by (transport)",
     "legendFormat": "{{transport}}"
    }
   ]
  },
  {
   "title": "Disconnect by server count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(round(rate(centrifugo_client_num_server_disconnects{instance=~\"$instance\"}[$__rate_interval])*60)) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Node action count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(round(rate(centrifugo_node_action_count{instance=~\"$instance\"}[$__rate_interval])*60)) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Proxy calls count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(round(rate(centrifugo_proxy_duration_seconds_count{instance=~\"$instance\"}[$__rate_interval])*60)) by (protocol, type)",
     "legendFormat": "{{protocol}}://{{type}}"
    }
   ]
  },
  {
   "title": "Proxy call errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(round(rate(centrifugo_proxy_errors{instance=~\"$instance\"}[$__rate_interval])*60)) by (protocol, type)",
     "legendFormat": "{{protocol}}://{{type}}"
    }
   ]
  },
  {
   "title": "Proxy calls time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(centrifugo_proxy_duration_seconds{quantile=\"$quantile\", instance=~\"$instance\"}) by (protocol, type)",
     "legendFormat": "{{protocol}}://{{type}}"
    }
   ]
  },
  { "title": "Go runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Go goroutines",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Go GC duration 0.75 quantile",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{quantile=\"0.75\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Process open file descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Process OS threads created",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_threads{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Process resident memory usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}