{
 "title": "Data Pipeline / Customer Ingestion Stats",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "tenant_id",
    "query": {
     "query": "label_values(ingestion_tenant_kilobytes,  tenant_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "MBs ingestion",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(ingestion_tenant_kilobytes{tenant_id=\"$tenant_id\"}[$__range])) / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Ingestion GBs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ingestion_tenant_kilobytes{tenant_id=\"$tenant_id\"}[$__range])) / 1024 / 1024"
    }
   ]
  },
  {
   "title": "GBs by job",
   "type": "stat",
   "gridPos": { "h": 25, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ingestion_tenant_kilobytes{tenant_id=\"$tenant_id\"}[$__range])) by (job) / 1024 / 1024",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "GBs per endpoint",
   "type": "stat",
   "gridPos": { "h": 25, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ingestion_tenant_kilobytes{tenant_id=\"$tenant_id\"}[$__range])) by (path) / 1024 / 1024",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "GBs per group",
   "type": "stat",
   "gridPos": { "h": 25, "w": 12, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ingestion_tenant_kilobytes{tenant_id=\"$tenant_id\"}[$__range])) by (group) / 1024 / 1024",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "GBs per provider",
   "type": "stat",
   "gridPos": { "h": 25, "w": 12, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ingestion_tenant_kilobytes{tenant_id=\"$tenant_id\"}[$__range])) by (provider) / 1024 / 1024",
     "legendFormat": "{{provider}}"
    }
   ]
  }
 ]
}