{
 "title": "Data Pipeline / Demultiplexers",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "type", "query": "file,windows" }
  ]
 },
 "panels": [
  {
   "title": "Active Processors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count(up{service=~\"${type}.*-events--demultiplexer\"}) by (kubernetes_pod_name))"
    }
   ]
  },
  {
   "title": "Processor CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"cynet\", pod=~\"${type}.*demultiplexer-.*\", container!=\"POD\"}) by (pod)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests_cpu_cores{namespace=\"cynet\", pod=~\"${type}.*demultiplexer-.*\", container!=\"POD\"})\n",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits_cpu_cores{namespace=\"cynet\", pod=~\"${type}.*demultiplexer-.*\", container!=\"POD\"})\n",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Processor backlog",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_subscription_back_log{subscription=~\".*${type}-events-processor\"})"
    }
   ]
  },
  {
   "title": "Dead letter backlog",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(pulsar_msg_backlog{topic=\"persistent://cynet/dlq/${type}-events-raw.*\"})"
    }
   ]
  },
  {
   "title": "Processor read/write/fail",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(processor_read{service=~\"${type}-events--demultiplexer\"}[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(processor_write{service=~\"${type}-events--demultiplexer\"}[5m]))",
     "legendFormat": "write"
    },
    {
     "expr": "sum(rate(processor_failed{service=~\"${type}-events--demultiplexer\"}[5m]))",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "Total Published",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(pulsar_client_messages_published{service=~\"${type}-events--demultiplexer\"})"
    }
   ]
  }
 ]
}