{
 "title": "Data Pipeline / Global View",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "provider",
    "query": {
     "query": "label_values(provider_requests_total, provider)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(provider_requests_total,  namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(provider_requests_total,  job)"
    }
   },
   { "name": "log_level", "query": "error" }
  ]
 },
 "panels": [
  {
   "title": "Ingress success rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{ingress=~\".*inge.*\",ingress!~\".*pcq.*\",status!~\"[4-5].*\"}[2m])) by (ingress) / sum(rate(nginx_ingress_controller_requests{ingress=~\".*inge.*\",ingress!~\".*pcq.*\"}[2m])) by (ingress)",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  {
   "title": "Subscription Backlog",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pulsar_subscription_back_log{kubernetes_namespace=\"$namespace\"}) by (subscription) > 50000",
     "legendFormat": "{{subscription}}"
    }
   ]
  },
  {
   "title": "Error/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", job=~\"$namespace/.*(sink|policies|ingestion|demultiplexer|.*download.*)\"}[5m] |= \"error\" )) by (job) ",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Service log",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{job=~\".*$service.*\"} |= \"$log_level\""
    }
   ]
  },
  { "title": "$provider", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Ingestion requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(provider_requests_total{container=\"ingestion\",provider=~\"${provider}\"}[$__range]))",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "Demultiplexer Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(provider_requests_total{provider=~\"${provider}\", service=~\".*-events-demultiplexer\"}[$__range]))",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "Downloader Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(provider_requests_total{provider=~\"${provider}\", container=\"download-service\"}[$__range]))",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "Sink Read",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(provider_requests_total{provider=~\"${provider}\",job=~\".*sink.*\"}[$__range])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Ingestion Sent Success",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(provider_sent_result_total{container=\"ingestion\",provider=~\"${provider}\", result=\"success\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Demultiplexer Sent Success",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(provider_sent_result_total{provider=~\"${provider}\", service=~\".*-events-demultiplexer\", result=\"success\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Downloader Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(provider_requests_total{provider=~\"${provider}\", container=\"download-service\"}[$__range]))",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "Sink Write",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(provider_sent_result_total{provider=~\"${provider}\", job=~\".*sink.*\", result=\"success\"}[$__range])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Ingestion Sent Failure",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(provider_sent_result_total{container=\"ingestion\",provider=~\"${provider}\", result=\"failure\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Demultiplexer Sent Failure",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(provider_sent_result_total{provider=~\"${provider}\", service=~\".*-events-demultiplexer\", result=\"failure\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Download Sent Failure",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(provider_sent_result_total{provider=~\"${provider}\", container=\"download-service\", result=\"failure\"}[$__range]))",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "Sink Failures",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(provider_sent_result_total{provider=~\"${provider}\", job=~\".*sink.*\", status=\"failure\"}[$__range])) by (service)"
    }
   ]
  }
 ]
}