{
 "title": "Data Pipeline / Gubernator",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "All GRPC requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(gubernator_grpc_request_counts{job=\"gubernator\"}[5m]))"
    }
   ]
  },
  {
   "title": "All GRPC requests failures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(gubernator_grpc_request_counts{status=\"failed\"}[5m]))"
    }
   ]
  },
  {
   "title": "GetPeerRateLimits",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(gubernator_grpc_request_counts{method=\"/pb.gubernator.PeersV1/GetPeerRateLimits\"}[5m]))"
    }
   ]
  },
  {
   "title": "GetPeerRateLimits",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(gubernator_grpc_request_counts{method=\"/pb.gubernator.PeersV1/GetPeerRateLimits\"}[5m]))"
    }
   ]
  },
  {
   "title": "Over Limit",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(gubernator_over_limit_counter[5m]))"
    }
   ]
  }
 ]
}