{
 "title": "Data Pipeline / Ingestion",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Ingestion Nginx Requests Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests{ingress=~\".*ingestion.*\"}[2m])) by (ingress), 0.001)"
    }
   ]
  },
  {
   "title": "Ingestion Open Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(go_fasthttp_open_connections)",
     "legendFormat": "avg-open-connections"
    },
    {
     "expr": "max(go_fasthttp_open_connections)",
     "legendFormat": "max-open-connections"
    },
    {
     "expr": "sum(go_fasthttp_open_connections)",
     "legendFormat": "sum-open-connections"
    }
   ]
  },
  {
   "title": "Requests per provider",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (provider) (rate(provider_requests_total{}[1m]))"
    }
   ]
  },
  {
   "title": "Ingestion CPU in CPU unit",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"ingestion.*\",  image!=\"\", container!=\"POD\"}[5m])",
     "legendFormat": "container usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_cpu_cores{pod=~\"ingestion.*\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{pod=~\"ingestion.*\", container!=\"POD\", image!=\"\"}[5m])",
     "legendFormat": "throttled"
    }
   ]
  },
  {
   "title": "Ingestion Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod=~\"ingestion.*\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_swap{pod=~\"ingestion.*\"}) by (pod)"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{pod=~\"ingestion.*\"}) by (pod)",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(container_spec_memory_reservation_limit_bytes{pod=~\"ingestion.*\"}) by (pod)",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "Ingestion producer Errors rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pulsar_client_producer_errors[5m])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Ingestion CPU percentage usage ",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum(   rate(container_cpu_system_seconds_total{namespace!~\"kube-system\", pod=~\"ingestion.*\"}[5m])) by (pod_name)\n",
     "legendFormat": "system-{{pod}}"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_user_seconds_total{namespace!~\"kube-system\", pod=~\"ingestion.*\"}[5m])) by (pod)",
     "legendFormat": "user"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_cfs_throttled_seconds_total{namespace!~\"kube-system\", pod=~\"ingestion.*\"}[5m])) by (pod)",
     "legendFormat": "throttled"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_usage_seconds_total{namespace!~\"kube-system\", pod=~\"ingestion.*\"}[5m])) by (pod)"
    }
   ]
  },
  {
   "title": "Ingestion Number of Pods",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{job=\"ingestion\"})"
    }
   ]
  },
  {
   "title": "Ingestion  unmarshal errors",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time({job=\"cynet/ingestion\"}|=\"Failed to unmarshal message\"[5m])"
    }
   ]
  },
  {
   "title": "Ingestion producer error",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(pulsar_client_producer_errors)"
    }
   ]
  },
  {
   "title": "Ingestion: All errors",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time({job=\"cynet/ingestion\"} |= \"level=error\"[5m])"
    }
   ]
  }
 ]
}