{
 "title": "Data Pipeline / Ingestion Request Buckets",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "path",
    "query": {
     "query": "label_values(http_request_size_kb_count, path)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(http_request_size_kb_count, namespace)"
    }
   },
   {
    "name": "pcq_type",
    "query": {
     "query": "label_values(fs_pcq_length_kb_bucket, type)"
    }
   },
   {
    "name": "event_type",
    "query": {
     "query": "label_values(eps_events_on_bundle_count, event_type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "request size KB",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(http_request_size_kb_bucket{namespace=\"${namespace}\", path=\"${path}\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "PCQs size KB",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(fs_pcq_length_kb_bucket{type=\"$pcq_type\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(http_request_size_kb_count{namespace=\"${namespace}\"}) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Big messages handled by ingestion",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ingestion_big_messages{namespace=\"cynet\"}) by (type)"
    }
   ]
  },
  {
   "title": "Events in bundle ${event_type}",
   "type": "bargauge",
   "description": "how many messages were bundled in EPS payload for event type: ${event_type}",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(eps_events_on_bundle_bucket{namespace=\"${namespace}\", event_type=\"${event_type}\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}