{
 "title": "Data Pipeline / PCQ pulsar by client",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "topic",
    "query": {
     "query": "label_values(pulsar_in_messages_total{topic=~\".*pcq.*\",namespace=\"cynet/pcq-tenant\"},  topic)\n"
    }
   },
   { "name": "datasource", "query": "prometheus" },
   { "name": "provider", "query": "alerts,data,exceptions" }
  ]
 },
 "panels": [
  { "title": "pcq pulsar per topic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "pulsar_in_messages_total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "pulsar_in_messages_total{topic=~\"${topic}\",kubernetes_namespace=\"pulsar-pcq-default\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "pulsar_out_messages_total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "pulsar_out_messages_total{topic=~\"${topic}\",kubernetes_namespace=\"pulsar-pcq-default\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "pulsar_consumers_count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "pulsar_consumers_count{topic=~\"$topic\",kubernetes_namespace=\"pulsar-pcq-default\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "pulsar_subscription_back_log",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 10 },
   "targets": [
    {
     "expr": "pulsar_subscription_back_log{topic=~\"${topic}\",kubernetes_namespace=\"pulsar-pcq-default\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "pcq alert converter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Alert converter requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(provider_requests_total{container=\"pcq-alert-converter\",provider=\"alerts\"}[$__range]))",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "Alert converter  Subscription Backlog",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pulsar_subscription_back_log{kubernetes_namespace=\"cynet\",subscription=\"alerts\"})",
     "legendFormat": "{{subscription}}"
    }
   ]
  },
  {
   "title": "Alert converter Sent Success",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(provider_sent_result_total{container=\"pcq-alert-converter\",provider=\"alerts\", result=\"success\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Alert converter  Sent Failure",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(provider_sent_result_total{container=\"pcq-alert-converter\",provider=\"alerts\", result=\"failure\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Ingestion $provider",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true
  },
  {
   "title": "Ingestion Sent Success",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(provider_sent_result_total{container=\"ingestion\",provider=~\"${provider}\", result=\"success\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Ingress success rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 4, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{ingress=~\".*inge.*pcq.*\",status!~\"[4-5].*\"}[2m])) by (ingress) / sum(rate(nginx_ingress_controller_requests{ingress=~\".*inge.*pcq.*\"}[2m])) by (ingress)",
     "legendFormat": "{{ingress}}"
    },
    {}
   ]
  },
  {
   "title": "Ingestion requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(provider_requests_total{container=\"ingestion\",provider=~\"${provider}\"}[$__range]))",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "Ingestion Sent Failure",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(provider_sent_result_total{container=\"ingestion\",provider=~\"${provider}\", result=\"failure\"}[$__range]))"
    }
   ]
  }
 ]
}