{
 "title": "Data Pipeline / PCQ Global View",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "provider",
    "query": {
     "query": "label_values(provider_requests_total, provider)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(provider_requests_total,  namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(provider_requests_total, job)"
    }
   },
   { "name": "log_level", "query": "error" }
  ]
 },
 "panels": [
  {
   "title": "Service log",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  { "title": "$provider", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }, "repeat": "provider" },
  {
   "title": "Ingress Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{ingress!~\".*pcq.*\",ingress=~\".*ing.*\",status!~\"[4-5].*\"}[2m])) by (ingress) / sum(rate(nginx_ingress_controller_requests{ingress!~\".*pcq.*\",ingress=~\".*ing.*\"}[2m])) by (ingress)",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  {
   "title": "Subscription Backlog",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pulsar_subscription_back_log{kubernetes_namespace=\"$namespace\", subscription=\"alertlogonly\"}) by (subscription) > 50000",
     "legendFormat": "{{subscription}}"
    },
    {
     "expr": "sum(pulsar_subscription_back_log{kubernetes_namespace=\"$namespace\", subscription=\"pcq-log-only-elastic-sink\"}) by (subscription) > 50000"
    }
   ]
  },
  {
   "title": "Error/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Ingestion requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(provider_requests_total{container=\"ingestion\", provider=\"${provider}\"}[1m]))",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "Converter messages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(provider_requests_total{provider=\"${provider}\", service=\"pcq-alert-converter-logonly\"}[1m]))",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "Sink Read",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(provider_requests_total{provider=\"${provider}\", job=\"pcq-log-only-alerts-sink\"}[5m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Ingestion Sent Success",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(provider_sent_result_total{container=\"ingestion\",provider=\"${provider}\", result=\"success\"}[1m]))"
    }
   ]
  },
  {
   "title": "Converter Sent Success",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(provider_sent_result_total{provider=\"${provider}\", service=\"pcq-alert-converter-logonly\", result=\"success\"}[1m]))",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "Sink Write",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(provider_sent_result_total{provider=\"${provider}\", job=\"pcq-log-only-alerts-sink\", result=\"success\"}[5m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Ingestion Sent Failure",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(provider_sent_result_total{container=\"ingestion\",provider=\"${provider}\", result=\"failure\"}[1m]))"
    }
   ]
  },
  {
   "title": "Converter Sent Failure",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(provider_sent_result_total{provider=\"${provider}\", service=\"pcq-alert-converter-logonly\", result=\"failure\"}[1m]))",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "Sink Failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(provider_sent_result_total{provider=\"${provider}\", job=\"pcq-log-only-alerts-sink\", status=\"failure\"}[5m])) by (service)"
    }
   ]
  }
 ]
}