{
 "title": "Data Pipeline / Global View",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "provider",
    "query": {
     "query": "label_values(provider_requests_total, provider)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(provider_requests_total,  namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(provider_requests_total,  job)"
    }
   },
   { "name": "log_level", "query": "error" }
  ]
 },
 "panels": [
  {
   "title": "Ingress success rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{ingress=~\".*inge.*\",status!~\"[4-5].*\"}[2m])) by (ingress) / sum(rate(nginx_ingress_controller_requests{ingress=~\".*inge.*\"}[2m])) by (ingress)",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  {
   "title": "Subscription Backlog",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pulsar_subscription_back_log{kubernetes_namespace=\"$namespace\"}) by (subscription) > 50000",
     "legendFormat": "{{subscription}}"
    }
   ]
  },
  {
   "title": "Error/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", job=~\"$namespace/.*(sink|policies|ingestion|demultiplexer|.*download.*)\"}[5m] |= \"error\" )) by (job) ",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Service log",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{job=~\".*$service.*\"} |= \"$log_level\""
    }
   ]
  },
  { "title": "$provider", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }, "repeat": "provider" },
  {
   "title": "Ingestion requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(provider_requests_total{container=\"ingestion\",provider=\"${provider}\"}[1m]))",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "Demultiplexer Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(provider_requests_total{provider=\"${provider}\", service=~\".*-events-demultiplexer\"}[1m]))",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "Policy Executer Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(provider_requests_total{provider=\"${provider}\", container=\"policy-executer\"}[1m]))",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "Downloader Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(provider_requests_total{provider=\"${provider}\", container=\"download-service\"}[1m])",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "Sink Read",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(provider_requests_total{provider=\"${provider}\", job=~\".*sink.*\"}[5m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Ingestion Sent Success",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(provider_sent_result_total{container=\"ingestion\",provider=\"${provider}\", result=\"success\"}[1m]))"
    }
   ]
  },
  {
   "title": "Demultiplexer Sent Success",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(provider_sent_result_total{provider=\"${provider}\", service=~\".*-events-demultiplexer\", result=\"success\"}[1m]))"
    }
   ]
  },
  {
   "title": "Policy Executer Success",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(provider_sent_result_total{provider=\"${provider}\", container=\"policy-executer\", result=\"success\"}[1m]))"
    }
   ]
  },
  {
   "title": "Downloader Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(provider_requests_total{provider=\"${provider}\", container=\"download-service\"}[1m])",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "Sink Write",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(provider_sent_result_total{provider=\"${provider}\", job=~\".*sink.*\", result=\"success\"}[5m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Ingestion Sent Failure",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(provider_sent_result_total{container=\"ingestion\",provider=\"${provider}\", result=\"failure\"}[1m]))"
    }
   ]
  },
  {
   "title": "Demultiplexer Sent Failure",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(provider_sent_result_total{provider=\"${provider}\", service=~\".*-events-demultiplexer\", result=\"failure\"}[1m]))"
    }
   ]
  },
  {
   "title": "Policy Executer Sent Failure",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(provider_sent_result_total{provider=\"${provider}\", container=\"policy-executer\", result=\"failure\"}[1m]))"
    }
   ]
  },
  {
   "title": "Download Sent Failure",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(provider_sent_result_total{provider=\"${provider}\", container=\"download-service\", result=\"failure\"}[1m]))",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "Sink Failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(provider_sent_result_total{provider=\"${provider}\", job=~\".*sink.*\", status=\"failure\"}[5m])) by (service)"
    }
   ]
  },
  {
   "title": "Click Sink Write",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(provider_sent_result_total{provider=\"generic\", job=~\".*click-sink.*\", result=\"success\"}[5m])) by (service)",
     "legendFormat": "{{service}}"
    },
    {
     "expr": "sum(rate(provider_sent_result_total{provider=\"generic\", job=~\".*click-sink.*\", result=\"failure\"}[5m])) by (service)",
     "legendFormat": "{{service}}-Errors"
    }
   ]
  }
 ]
}