{
 "title": "Data Pipeline / Policy executers",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "policy_type", "label": "Policy Type", "query": "file,windows,external" }
  ]
 },
 "panels": [
  {
   "title": "Policy Executer goroutines",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{pod=~\"${policy_type}.*-events--policies.*\"}"
    }
   ]
  },
  {
   "title": "Policy Executers Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod=~\"${policy_type}.*-events--policies.*\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_swap{pod=~\"${policy_type}.*-events--policies.*\"}) by (pod)"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{pod=~\"${policy_type}.*-events--policies.*\"}) by (pod)",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(container_spec_memory_reservation_limit_bytes{pod=~\"${policy_type}.*-events--policies.*\"}) by (pod)",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "filtered_events_total",
   "type": "graph",
   "description": "write rate for a sink a cross all of its instances",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (result) (rate(filtered_events_total{service=\"${policy_type}-events--policies\"}[1m]))",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Filter backlog",
   "type": "graph",
   "description": "write rate for a sink a cross all of its instances",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_subscription_back_log{topic=~\"persistent://cynet/default/${policy_type}-events-raw-p-partition-.*\", subscription=~\".*${policy_type}-events-sink\"})"
    }
   ]
  },
  {
   "title": "Policy executers CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"cynet\", pod=~\"${policy_type}.*-events--policies.*\", container!=\"POD\"}) by (pod)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests_cpu_cores{namespace=\"cynet\", pod=~\"${policy_type}.*-events--policies.*\", container!=\"POD\"})\n",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits_cpu_cores{namespace=\"cynet\", pod=~\"${policy_type}.*-events--policies.*\", container!=\"POD\"})\n",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Policy Executers",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(up{job=\"${policy_type}-events--policies\"}) by (kubernetes_pod_name))"
    }
   ]
  },
  {
   "title": "Recived/published",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pulsar_client_messages_published{topic=\"persistent://cynet/default/${policy_type}-events-p\"}[1m]))",
     "legendFormat": "published"
    },
    {
     "expr": "sum(rate(pulsar_client_messages_received{topic=\"persistent://cynet/default/${policy_type}-events-raw-p\"}[1m]))",
     "legendFormat": "consumed"
    }
   ]
  }
 ]
}