{
 "title": "Data Pipeline / Query API - GraphQL",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(provider_requests_total{provider=\"file_events\", service=~\".*-query-api\"}[1m]))",
     "legendFormat": "file_events requests"
    }
   ]
  },
  {
   "title": "Success Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(provider_sent_result_total{provider=\"file_events\", service=~\".*-query-api\", result=\"success\"}[1m]))",
     "legendFormat": "success responses"
    }
   ]
  },
  {
   "title": "Failure Responses",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(provider_sent_result_total{provider=\"file_events\", service=~\".*-query-api\", result=\"failure\"}[1m]))",
     "legendFormat": "failure responses"
    }
   ]
  }
 ]
}