{
 "title": "Data Pipeline / Rate Limiting",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "provider",
    "query": {
     "query": "label_values(ingestion_requests, provider)"
    }
   },
   {
    "name": "clientId",
    "label": "client id",
    "query": {
     "query": "label_values(ingestion_requests, client_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "## External Events\nIs limited to 1500 hits per 15 seconds\n## EPS source Events\nIs limited to (number_of_endpoints * 200) hits per 15 seconds\n\n## Note\nA hit is derived from the payload size. Each 1K counts as a hit"
   }
  },
  {
   "title": "Number Requests Limited By client Id and Provider",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "sum by (client_id,provider) (increase(ingestion_requests{rate_limited=\"true\",provider=~\"${provider}\",client_id=~\"${clientId}\"}[$__range])>0)"
    }
   ]
  },
  {
   "title": "Providers Rate Limited",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 5, "y": 8 },
   "targets": [
    {
     "expr": "sum by (provider) (increase(ingestion_requests{rate_limited=\"true\",provider=~\"${provider}\",client_id=~\"${clientId}\"}[$__range])>0)",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Number Requests Limited By client Id and Provider",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (client_id) (increase(ingestion_requests{rate_limited=\"true\",provider=~\"${provider}\",client_id=~\"${clientId}\"}[$__range])>0))"
    }
   ]
  },
  {
   "title": "Requests Allowed",
   "type": "table",
   "gridPos": { "h": 6, "w": 16, "x": 5, "y": 15 },
   "targets": [
    {
     "expr": "sum by (client_id,provider) (increase(ingestion_requests{rate_limited=\"false\",provider=~\"${provider}\",client_id=~\"${clientId}\"}[$__range])>0)",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Number of request per minute",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 16, "x": 5, "y": 21 },
   "targets": [
    {
     "expr": "sum(increase(ingestion_requests{rate_limited=\"false\",provider=~\"${provider}\",client_id=~\"${clientId}\"}[1m])) by (client_id,provider)"
    }
   ]
  }
 ]
}