{
 "title": "Data Pipeline / Sinks Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "sink_static_type", "label": "Sink Type", "query": "file,windows,external" }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sink Metrics Rate",
   "type": "graph",
   "description": "write rate for a sink a cross all of its instances",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(sink_write_total{service=~\"${sink_static_type}.*-events--sink\"}[5m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum (rate(sink_read_total{service=~\"${sink_static_type}.*-events--sink\"}[5m]))",
     "legendFormat": "received"
    },
    {
     "expr": "sum (rate(sink_failed_total{service=~\"${sink_static_type}.*-events--sink\"}[5m]))",
     "legendFormat": "exceptions"
    }
   ]
  },
  {
   "title": "Sink Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"${sink_static_type}.*-events--sink.*\", container!=\"POD\", container!=\"\", }) by (pod)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests_memory_bytes{pod=~\"${sink_static_type}.*-events--sink.*\"})\n",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Sink backlog",
   "type": "graph",
   "description": "write rate for a sink a cross all of its instances",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_subscription_back_log{subscription=~\".*${sink_static_type}-events-sink\"})",
     "legendFormat": "backlog"
    }
   ]
  },
  {
   "title": "Sinks CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"cynet\", pod=~\"${sink_static_type}.*-events--sink.*\", container!=\"POD\"}) by (pod)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests_cpu_cores{namespace=\"cynet\", pod=~\"${sink_static_type}.*-events--sink.*\", container!=\"POD\"})\n",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits_cpu_cores{namespace=\"cynet\", pod=~\"${sink_name}.*\", container!=\"POD\"})\n",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Dead letter backlog",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(pulsar_msg_backlog{topic=\"persistent://cynet/dlq/${sink_static_type}-events-sink-DLQ\"})"
    }
   ]
  },
  {
   "title": "total written to ES",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sink_write_total{ service=~\"${sink_static_type}.*-events--sink\"})"
    }
   ]
  },
  {
   "title": "Sinks",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(up{service=~\"${sink_static_type}.*-events--sink\"}) by (kubernetes_pod_name))"
    }
   ]
  }
 ]
}