{
 "title": "Data Pipeline / Top Data Producers",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "tenant_drill_down" },
   { "name": "topK", "query": "10" }
  ]
 },
 "panels": [
  {
   "title": "total GB",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk($topK,sum(increase(ingestion_tenant_kilobytes[$__range])) by (tenant_id)) / 1024 / 1024",
     "legendFormat": "{{tenant_id}}"
    }
   ]
  },
  {
   "title": "mb/sec",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "topk($topK, sum(rate(ingestion_tenant_kilobytes[5m])) by (tenant_id)) / 1024",
     "legendFormat": "{{tenant_id}}"
    }
   ]
  },
  {
   "title": "drill down for '$tenant_drill_down'",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(ingestion_tenant_kilobytes{tenant_id=\"$tenant_drill_down\"}[5m])) by (path)"
    }
   ]
  }
 ]
}