{
 "title": "Clickhouse / Altinity ClickHouse Operator Dashboard",
 "description": "Alitinity Clickhouse Operator metrics exported by Monitoring Agent",
 "tags": [
  "Altinity",
  "clickhouse",
  "operator"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "exported_namespace",
    "label": "K8S Namespace",
    "query": "label_values(chi_clickhouse_metric_Uptime, exported_namespace)"
   },
   {
    "name": "chi",
    "label": "K8S Clickhouse Installation",
    "query": "label_values(chi_clickhouse_metric_Uptime, chi)"
   },
   {
    "name": "hostname",
    "label": "Server",
    "query": "label_values(chi_clickhouse_metric_Uptime, hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "table",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 0 },
   "targets": [
    { "expr": "chi_clickhouse_metric_Uptime", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "ReadOnly replicas",
   "type": "singlestat",
   "description": "Check Zookeeper connection, Disk Free space and network interconnection between replicas ASAP",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(chi_clickhouse_metric_ReadonlyReplica{exported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\",hostname=~\"[[hostname]]\"})"
    }
   ]
  },
  {
   "title": "Version",
   "type": "table",
   "description": "For example, version 11.22.33 is translated to 11022033",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "chi_clickhouse_metric_VersionInteger",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "description": "Show different types of connections for each server",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "chi_clickhouse_metric_TCPConnection{exported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\",hostname=~\"[[hostname]]\"}",
     "legendFormat": "tcp {{hostname}}"
    },
    {
     "expr": "chi_clickhouse_metric_HTTPConnection{exported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\",hostname=~\"[[hostname]]\"}",
     "legendFormat": "http {{hostname}}"
    },
    {
     "expr": "chi_clickhouse_metric_InterserverConnection{exported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\",hostname=~\"[[hostname]]\"}",
     "legendFormat": "interserver {{hostname}}"
    },
    {
     "expr": "chi_clickhouse_metric_MySQLConnection{exported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\",hostname=~\"[[hostname]]\"}",
     "legendFormat": "mysql {{hostname}}"
    }
   ]
  },
  {
   "title": "Replication and ZooKeeper Exceptions",
   "type": "graph",
   "description": "Show readonly and partial shutdown replicas, zookeeer exceptions, zookeeer sessions, zookeeper init requests",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "chi_clickhouse_metric_ReadonlyReplica{exported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\",hostname=~\"[[hostname]]\"}",
     "legendFormat": "ReadonlyReplica {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_ReplicaPartialShutdown{exported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\",hostname=~\"[[hostname]]\"}[5m])",
     "legendFormat": "ReplicaPartialShutdown {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_ZooKeeperUserExceptions{exported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\",hostname=~\"[[hostname]]\"}[5m])",
     "legendFormat": "ZooKeeperUserExceptions  {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_ZooKeeperInit{exported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\",hostname=~\"[[hostname]]\"}[5m])",
     "legendFormat": "ZooKeeperInit {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_metric_ZooKeeperSession{exported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\",hostname=~\"[[hostname]]\"}[5m])",
     "legendFormat": "ZooKeeperSession  {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_ZooKeeperHardwareExceptions{exported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\",hostname=~\"[[hostname]]\"}[5m])",
     "legendFormat": "ZooKeeperHardwareExceptions  {{hostname}}"
    }
   ]
  },
  {
   "title": "DNS and Distributed Connection Errors",
   "type": "graph",
   "description": "Show DNS errors and distributed server-server connections failures",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(chi_clickhouse_event_NetworkErrors{exported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\",hostname=~\"[[hostname]]\"}[1m])",
     "legendFormat": "DNSErrors {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_DistributedConnectionFailAtAll{xported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\",hostname=~\"[[hostname]]\"}[1m])",
     "legendFormat": "DistributedConnectionFailAtAll {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_DistributedConnectionFailTry{exported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\",hostname=~\"[[hostname]]\"}[1m])",
     "legendFormat": "DistributedConnectionFailTry {{hostname}}"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "graph",
   "description": "Number of queries started to be interpreted and maybe executed. Does not include queries that are failed to parse, that are rejected due to AST size limits; rejected due to quota limits or limits on number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(chi_clickhouse_event_Query{exported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\",hostname=~\"[[hostname]]\"}[1m])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Compressed Read Buffer",
   "type": "graph",
   "description": "Show how much bytes read and decompress via compressed buffer on each server in cluster",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(chi_clickhouse_event_CompressedReadBufferBytes{exported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\",hostname=~\"[[hostname]]\"}[1m])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Memory for Queries",
   "type": "graph",
   "description": "Total amount of memory (bytes) allocated in currently executing queries. \n\nNote that some memory allocations may not be accounted.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "chi_clickhouse_metric_MemoryTracking{exported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\",hostname=~\"[[hostname]]\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Insert Requests",
   "type": "graph",
   "description": "## Tracks amount of inserted data.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(chi_clickhouse_event_InsertQuery{exported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\",hostname=~\"[[hostname]]\"}[5m])",
     "legendFormat": "Insert queries {{hostname}}"
    }
   ]
  },
  {
   "title": "Rows Inserted",
   "type": "graph",
   "description": "## Tracks rows of inserted data.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(chi_clickhouse_event_InsertedRows{exported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\",hostname=~\"[[hostname]]\"}[1m])",
     "legendFormat": "Insert rows {{hostname}}"
    }
   ]
  },
  {
   "title": "Bytes Inserted",
   "type": "graph",
   "description": "## Tracks amount of inserted data.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(chi_clickhouse_event_InsertedBytes{exported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\",hostname=~\"[[hostname]]\"}[1m])",
     "legendFormat": "Insert bytes {{hostname}}"
    }
   ]
  },
  {
   "title": "Background Tasks",
   "type": "graph",
   "description": "BackgroundPoolTask\t\n---\nNumber of active tasks in BackgroundProcessingPool (merges, mutations, fetches, or replication queue bookkeeping)\n\n\nBackgroundMovePoolTask\n---\nNumber of active tasks in BackgroundProcessingPool for moves\n\n\nBackgroundSchedulePoolTask\t\n---\nA number of active tasks in BackgroundSchedulePool. This pool is used for periodic ReplicatedMergeTree tasks, like cleaning old data parts, altering data parts, replica re-initialization, etc.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "chi_clickhouse_metric_BackgroundPoolTask{exported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\",hostname=~\"[[hostname]]\"}",
     "legendFormat": "merge, mutate, fetch {{hostname}}"
    },
    {
     "expr": "chi_clickhouse_metric_BackgroundSchedulePoolTask{exported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\",hostname=~\"[[hostname]]\"}",
     "legendFormat": "clean, alter, replica re-init {{hostname}}"
    },
    {
     "expr": "chi_clickhouse_metric_BackgroundMovePoolTask{exported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\",hostname=~\"[[hostname]]\"}",
     "legendFormat": "moves {{hostname}}"
    }
   ]
  },
  {
   "title": "Merges",
   "type": "graph",
   "description": "Show how intensive background merge processes",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "merges" }
   ],
   "targets": [
    {
     "expr": "rate(chi_clickhouse_event_Merge{exported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\",hostname=~\"[[hostname]]\"}[1m])",
     "legendFormat": "merges {{hostname}}"
    }
   ]
  },
  {
   "title": "Replication Queue",
   "type": "graph",
   "description": "## MemoryTrackingInBackgroundProcessingPool\t\n\nTotal amount of memory (bytes) allocated in background processing pool (that is dedicated for backround merges, mutations and fetches). \n\n\n## MemoryTrackingInBackgroundMoveProcessingPool\n\nTotal amount of memory (bytes) allocated in background processing pool (that is dedicated for backround moves). \n\n\n## MemoryTrackingInBackgroundSchedulePool\n\nTotal amount of memory (bytes) allocated in background schedule pool (that is dedicated for bookkeeping tasks of Replicated tables).\n\n\n## MemoryTrackingForMerges\n\nTotal amount of memory (bytes) allocated for background merges. Included in MemoryTrackingInBackgroundProcessingPool. \n\n\nNote that this values may include a drift when the memory was allocated in a context of background processing pool and freed in other context or vice-versa. This happens naturally due to caches for tables indexes and doesn't indicate memory leaks.\n",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "chi_clickhouse_metric_ReplicasMaxQueueSize{exported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\",hostname=~\"[[hostname]]\"}",
     "legendFormat": "queue size bytes {{hostname}}"
    },
    {}
   ]
  },
  {
   "title": "Active Parts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(hostname) (chi_clickhouse_table_parts{exported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\"})",
     "legendFormat": "Parts {{hostname}}"
    }
   ]
  },
  {
   "title": "Merged Rows",
   "type": "graph",
   "description": "Show how intensive background merge processes",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(chi_clickhouse_event_MergedRows{exported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\",hostname=~\"[[hostname]]\"}[1m])",
     "legendFormat": "rows {{hostname}}"
    }
   ]
  },
  {
   "title": "Mutations",
   "type": "graph",
   "description": "Number of mutations (ALTER DELETE/ALTER UPDATE)",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "chi_clickhouse_metric_PartMutation{exported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\",hostname=~\"[[hostname]]\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Zookeeper Requests",
   "type": "graph",
   "description": "Number of requests to ZooKeeper in fly.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "chi_clickhouse_metric_ZooKeeperRequest{exported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\",hostname=~\"[[hostname]]\"}"
    }
   ]
  },
  {
   "title": "Read/Write syscalls",
   "type": "graph",
   "description": "Read\nNumber of read (read, pread, io_getevents, etc.) syscalls in fly\n\nWrite\nNumber of write (write, pwrite, io_getevents, etc.) syscalls in fly",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "chi_clickhouse_metric_Read{exported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\",hostname=~\"[[hostname]]\"}",
     "legendFormat": "read {{hostname}}"
    },
    {
     "expr": "chi_clickhouse_metric_Write{exported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\",hostname=~\"[[hostname]]\"}",
     "legendFormat": "write {{hostname}}"
    }
   ]
  },
  {
   "title": "Marks Cache Hit Rate",
   "type": "graph",
   "description": "Show which percent of mark files (.mrk) read from memory instead of disk",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 39 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(chi_clickhouse_event_MarkCacheHits[1m]) / (rate(chi_clickhouse_event_MarkCacheHits[1m]) + rate(chi_clickhouse_event_MarkCacheMisses[1m]))",
     "legendFormat": "1m {{hostname}}"
    }
   ]
  },
  {
   "title": "Replication Jobs",
   "type": "graph",
   "description": "Show how intensive data exchange between replicas in parts",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short", "label": "parts" }
   ],
   "targets": [
    {
     "expr": "chi_clickhouse_metric_ReplicatedChecks{exported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\",hostname=~\"[[hostname]]\"}",
     "legendFormat": "check {{hostname}}"
    },
    {
     "expr": "chi_clickhouse_metric_ReplicatedFetch{exported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\",hostname=~\"[[hostname]]\"}",
     "legendFormat": "fetch {{hostname}}"
    },
    {
     "expr": "chi_clickhouse_metric_ReplicatedSend{exported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\",hostname=~\"[[hostname]]\"}",
     "legendFormat": "send {{hostname}}"
    }
   ]
  },
  {
   "title": "Replicated tables leaders",
   "type": "graph",
   "description": "Number of Replicated tables that are leaders. Leader replica is responsible for assigning merges, cleaning old blocks for deduplications and a few more bookkeeping tasks. There may be no more than one leader across all replicas at one moment of time. If there is no leader it will be elected soon or it indicate an issue.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "chi_clickhouse_metric_LeaderReplica{exported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\",hostname=~\"[[hostname]]\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Background Pools Memory",
   "type": "graph",
   "description": "## MemoryTrackingInBackgroundProcessingPool\t\n\nTotal amount of memory (bytes) allocated in background processing pool (that is dedicated for backround merges, mutations and fetches). \n\n\n## MemoryTrackingInBackgroundMoveProcessingPool\n\nTotal amount of memory (bytes) allocated in background processing pool (that is dedicated for backround moves). \n\n\n## MemoryTrackingInBackgroundSchedulePool\n\nTotal amount of memory (bytes) allocated in background schedule pool (that is dedicated for bookkeeping tasks of Replicated tables).\n\n\n## MemoryTrackingForMerges\n\nTotal amount of memory (bytes) allocated for background merges. Included in MemoryTrackingInBackgroundProcessingPool. \n\n\nNote that this values may include a drift when the memory was allocated in a context of background processing pool and freed in other context or vice-versa. This happens naturally due to caches for tables indexes and doesn't indicate memory leaks.\n",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 46 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "chi_clickhouse_metric_MemoryTrackingInBackgroundProcessingPool{exported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\",hostname=~\"[[hostname]]\"}",
     "legendFormat": "merge, mutate, fetch {{hostname}}"
    },
    {
     "expr": "chi_clickhouse_metric_MemoryTrackingInBackgroundMoveProcessingPool{exported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\",hostname=~\"[[hostname]]\"}",
     "legendFormat": "moves {{hostname}}"
    },
    {
     "expr": "chi_clickhouse_metric_MemoryTrackingInBackgroundSchedulePool{exported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\",hostname=~\"[[hostname]]\"}",
     "legendFormat": "alter, clean, replica re-init {{hostname}}"
    },
    {
     "expr": "chi_clickhouse_metric_MemoryTrackingForMerges{exported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\",hostname=~\"[[hostname]]\"}",
     "legendFormat": "merges {{hostname}}"
    }
   ]
  },
  {
   "title": "Monitoring Agent Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{service=\"clickhouse-operator-metrics\",}[1m])",
     "legendFormat": "GO malloc bytes / sec"
    },
    {
     "expr": "process_resident_memory_bytes{service=\"clickhouse-operator-metrics\"}",
     "legendFormat": "Process RSS Memory"
    }
   ]
  }
 ]
}