{
 "title": "Clickhouse Mitre2023",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "tenant",
    "query": "SELECT distinct toString(client_id) FROM mtr.file_events_dist"
   }
  ]
 },
 "panels": [
  {
   "title": "Pulasr Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_subscription_back_log{kubernetes_namespace=\"mitre2023\"}) by (subscription) > 20",
     "legendFormat": "{{subscription}}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "mtr",
     "dateTimeColDataType": "event_create_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    count() as file\nFROM mtr.file_events\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_create_time), 600) * 600) * 1000 as t,\n    count() as file\nFROM mtr.file_events\nWHERE event_create_time >= toDateTime(1675610218) AND event_create_time <= toDateTime(1676215018)\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "file_events"
    },
    {
     "database": "mtr",
     "dateColDataType": "dbDay",
     "dateTimeColDataType": "dbTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    count() as windows\nFROM mtr.windows_events\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dbTime), 600) * 600) * 1000 as t,\n    count() as windows\nFROM mtr.windows_events\nWHERE dbDay >= toDate(1675610218) AND dbDay <= toDate(1676215018) AND dbTime >= toDateTime(1675610218) AND dbTime <= toDateTime(1676215018)\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "windows_events"
    }
   ]
  },
  {
   "title": "Actions",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "database": "mtr",
     "dateTimeColDataType": "event_create_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    count(),\n    action\nFROM mtr.file_events\n\nWHERE $timeFilter\n\nGROUP BY\n    t,\n    action\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_create_time), 300) * 300) * 1000 as t,\n    count(),\n    action\nFROM mtr.file_events\n\nWHERE event_create_time >= toDateTime(1676163992) AND event_create_time <= toDateTime(1676207192)\n\nGROUP BY\n    t,\n    action\nORDER BY t",
     "round": "0s",
     "table": "file_events"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "mtr",
     "dateTimeColDataType": "ts",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    count(rule_id),\n    rule_id\nFROM mtr.alerts\nWHERE $timeFilter\nGROUP BY t,rule_id\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(ts), 900) * 900) * 1000 as t,\n    count(rule_id),\n    rule_id\nFROM mtr.alerts\nWHERE ts >= toDateTime(1676193623) AND ts <= toDateTime(1676215223)\nGROUP BY t,rule_id\nORDER BY t",
     "round": "0s",
     "table": "file_events"
    }
   ]
  },
  {
   "title": "Table stats",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "    select table,\n           sum(rows)                                            as rows,\n           max(modification_time)                               as latest_modification,\n           formatReadableSize(sum(bytes))                       as disk_size,\n           formatReadableSize(sum(primary_key_bytes_in_memory)) as primary_keys_size,\n           any(engine)                                          as engine,\n           sum(bytes)                                           as bytes_size\n    from system.parts\n    where active and database = currentDatabase()\n    group by database, table\n    ",
     "rawQuery": "select table,\n           sum(rows)                                            as rows,\n           max(modification_time)                               as latest_modification,\n           formatReadableSize(sum(bytes))                       as disk_size,\n           formatReadableSize(sum(primary_key_bytes_in_memory)) as primary_keys_size,\n           any(engine)                                          as engine,\n           sum(bytes)                                           as bytes_size\n    from system.parts\n    where active and database = currentDatabase()\n    group by database, table",
     "round": "0s"
    },
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "    select table  as mitre_table,\n           sum(rows)                                            as rows,\n           max(modification_time)                               as latest_modification,\n           formatReadableSize(sum(bytes))                       as disk_size,\n           formatReadableSize(sum(primary_key_bytes_in_memory)) as primary_keys_size,\n           any(engine)                                          as engine,\n           sum(bytes)                                           as bytes_size\n    from system.parts\n    where active and database = 'mtr'\n    group by database, table\n    ",
     "rawQuery": "select table  as mitre_table,\n           sum(rows)                                            as rows,\n           max(modification_time)                               as latest_modification,\n           formatReadableSize(sum(bytes))                       as disk_size,\n           formatReadableSize(sum(primary_key_bytes_in_memory)) as primary_keys_size,\n           any(engine)                                          as engine,\n           sum(bytes)                                           as bytes_size\n    from system.parts\n    where active and database = 'mtr'\n    group by database, table",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Memory stats",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "database": "system",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT metric,formatReadableSize(value)as size\nFROM system.metrics\nWHERE metric in( 'MemoryTrackingForMerges','MemoryTracking')\nORDER BY value DESC\nLIMIT 10\n    ",
     "rawQuery": "SELECT metric,formatReadableSize(value)as size\nFROM system.metrics\nWHERE metric in( 'MemoryTrackingForMerges','MemoryTracking')\nORDER BY value DESC\nLIMIT 10",
     "round": "0s",
     "table": "metrics"
    }
   ]
  },
  {
   "title": "Popular paths",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "database": "mtr",
     "dateTimeColDataType": "event_create_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    count(file_path) AS nt,\n    file_path\nFROM mtr.file_events_dist\nWHERE $timeFilter\nGROUP BY file_path\nHAVING nt > 100\nORDER BY nt DESC\nLIMIT 10\n",
     "rawQuery": "SELECT\n    count(file_path) AS nt,\n    file_path\nFROM mtr.file_events_dist\nWHERE event_create_time >= toDateTime(1676196170) AND event_create_time <= toDateTime(1676206970)\nGROUP BY file_path\nHAVING nt > 100\nORDER BY nt DESC\nLIMIT 10",
     "round": "0s",
     "table": "file_events"
    }
   ]
  }
 ]
}