{
 "title": "Pulsar / Auto Recovery Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "{cluster=~\".+\"}"
   },
   {
    "name": "kubernetes_pod_name",
    "label": "Bookie Recovery",
    "query": "replication_worker_NUM_BYTES_READ_count{cluster=~\"$cluster\", kubernetes_pod_name=~\".+\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Under-Replicated Ledgers count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(auditor_NUM_UNDER_REPLICATED_LEDGERS_count{cluster=~\"$cluster\", success=\"true\"})",
     "legendFormat": "$cluster"
    }
   ]
  },
  {
   "title": "Replication read throughput (bytes/s)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(replication_worker_NUM_BYTES_READ_count{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\", success=\"true\"}[1m])",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Replication read entry rate (entries/s)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(replication_worker_NUM_ENTRIES_READ{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[1m])",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Replication write throughput (bytes/s)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(replication_worker_NUM_BYTES_WRITTEN_count{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\", success=\"true\"}[1m])",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Replication write entry rate (entries/s)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(replication_worker_NUM_ENTRIES_WRITTEN{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[1m])",
     "legendFormat": "$cluster"
    }
   ]
  }
 ]
}