{
 "title": "Pulsar / Containers Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(up{app=\"pulsar\"}, kubernetes_pod_name)"
    }
   },
   {
    "name": "kubernetes_namespace",
    "query": {
     "query": "label_values(up{app=\"pulsar\"}, kubernetes_namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "pod" },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum(   rate(container_cpu_system_seconds_total{namespace!~\"$kubernetes_namespace\", pod=~\"$pod\"}[5m])) by (pod_name)\n",
     "legendFormat": "system"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_user_seconds_total{namespace!~\"$kubernetes_namespace\", pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "user"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_cfs_throttled_seconds_total{namespace!~\"$kubernetes_namespace\", pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "throttled"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod=~\"$pod\", namespace=~\"$kubernetes_namespace\"}) by (pod)",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum(container_memory_swap{pod=~\"$pod\", namespace=~\"$kubernetes_namespace\"}) by (pod)",
     "legendFormat": "Swap"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{pod=~\"$pod\", namespace=~\"$kubernetes_namespace\"}) by (pod)",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(container_spec_memory_reservation_limit_bytes{pod=~\"$pod\", namespace=~\"$kubernetes_namespace\"}) by (pod)",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8 * sum(rate(container_network_receive_bytes_total{pod=~\"$pod\", namespace=~\"$kubernetes_namespace\"}[5m])) by (pod)",
     "legendFormat": "In"
    },
    {
     "expr": "- 8 * sum(rate(container_network_transmit_bytes_total{pod=~\"$pod\", namespace=~\"$kubernetes_namespace\"}[5m])) by (pod)",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{pod=~\"$pod\", namespace=~\"$kubernetes_namespace\"}[5m])) by (pod,device)",
     "legendFormat": "Writes {{ device }}"
    },
    {
     "expr": "- sum(rate(container_fs_reads_bytes_total{pod=~\"$pod\", namespace=~\"$kubernetes_namespace\"}[5m])) by (pod,device)",
     "legendFormat": "Reads {{ device }}"
    }
   ]
  }
 ]
}