{
 "title": "Pulsar / Overview",
 "description": "Overview of Pulsar Cluster",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "kubernetes_namespace",
    "query": {
     "query": "label_values(pulsar_storage_size, kubernetes_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Kubernetes Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "count(node_cpu_seconds_total{mode=\"system\"})"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes)"
      }
     ]
    },
    {
     "title": "PersistentVolume Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 9, "x": 6, "y": 1 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 * (1 - (kubelet_volume_stats_available_bytes / on (persistentvolumeclaim) kubelet_volume_stats_capacity_bytes))",
       "legendFormat": "{{ persistentvolumeclaim }}"
      }
     ]
    },
    {
     "title": "Node Disk Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 * (node_filesystem_size_bytes - node_filesystem_avail_bytes)  / node_filesystem_size_bytes",
       "legendFormat": "{{ instance }} - {{ device }}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 * ( 1 - \n   ( sum(increase(node_cpu_seconds_total{mode=\"idle\"}[1m]))\n    / \n   sum(increase(node_cpu_seconds_total[1m]))\n  )\n)"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes) / sum(node_memory_MemTotal_bytes) * 100"
      }
     ]
    }
   ]
  },
  { "title": "Pulsar Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Zookeeper",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(up{job=\"zookeeper\", kubernetes_namespace=~\"$kubernetes_namespace\"}) by (kubernetes_pod_name))"
    }
   ]
  },
  {
   "title": "Bookies",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(up{job=\"bookie\", kubernetes_namespace=~\"$kubernetes_namespace\"}) by (kubernetes_pod_name))"
    }
   ]
  },
  {
   "title": "Brokers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(up{job=\"broker\", kubernetes_namespace=~\"$kubernetes_namespace\"}) by (kubernetes_pod_name))"
    }
   ]
  },
  {
   "title": "Proxies",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(up{job=\"proxy\", kubernetes_namespace=~\"$kubernetes_namespace\"}) by (kubernetes_pod_name))"
    }
   ]
  },
  {
   "title": "Functions",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(up{job=\"function\", kubernetes_namespace=~\"$kubernetes_namespace\"}) by (kubernetes_pod_name))"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pulsar_storage_size{job=~\"broker\", kubernetes_namespace=~\"$kubernetes_namespace\"}) by (cluster)"
    }
   ]
  },
  {
   "title": "Backlog (bytes)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pulsar_storage_backlog_size{job=~\"broker\", kubernetes_namespace=~\"$kubernetes_namespace\"}) by (cluster)"
    }
   ]
  },
  {
   "title": "Backlog (msgs)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pulsar_msg_backlog{job=~\"broker\", kubernetes_namespace=~\"$kubernetes_namespace\"}) by (cluster)"
    }
   ]
  },
  {
   "title": "Zookeeper Up",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * count(up{job=\"zookeeper\", kubernetes_namespace=~\"$kubernetes_namespace\"} == 1) / count(up{job=\"zookeeper\", kubernetes_namespace=~\"$kubernetes_namespace\"})"
    }
   ]
  },
  {
   "title": "Bookies Up",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * count(up{job=\"bookie\", kubernetes_namespace=~\"$kubernetes_namespace\"} == 1) / count(up{job=\"bookie\", kubernetes_namespace=~\"$kubernetes_namespace\"})"
    }
   ]
  },
  {
   "title": "Brokers Up",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * count(up{job=\"broker\", kubernetes_namespace=~\"$kubernetes_namespace\"} == 1) / count(up{job=\"broker\", kubernetes_namespace=~\"$kubernetes_namespace\"})"
    }
   ]
  },
  {
   "title": "Proxies Up",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * count(up{job=\"proxy\", kubernetes_namespace=~\"$kubernetes_namespace\"} == 1) / count(up{job=\"proxy\", kubernetes_namespace=~\"$kubernetes_namespace\"})"
    }
   ]
  },
  {
   "title": "Functions Up",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * count(up{job=\"function\", kubernetes_namespace=~\"$kubernetes_namespace\"} == 1) / count(up{job=\"function\", kubernetes_namespace=~\"$kubernetes_namespace\"})"
    }
   ]
  },
  { "title": "Messaging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Messaging Storage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_storage_size{job=~\"broker\", kubernetes_namespace=~\"$kubernetes_namespace\"}) by (cluster)",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "Message Backlog (size)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_storage_backlog_size{job=~\"broker\", kubernetes_namespace=~\"$kubernetes_namespace\"}) by (cluster)",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "Message Backlog (msgs)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_msg_backlog{job=~\"broker\", kubernetes_namespace=~\"$kubernetes_namespace\"}) by (cluster)",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "Message Rate (msg/s)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_rate_in{job=~\"broker\", kubernetes_namespace=~\"$kubernetes_namespace\"}) by (cluster)",
     "legendFormat": "{{ cluster }} - In"
    },
    {
     "expr": "sum(pulsar_rate_out{job=~\"broker\", kubernetes_namespace=~\"$kubernetes_namespace\"}) by (cluster)",
     "legendFormat": "{{ cluster }} - Out"
    }
   ]
  },
  {
   "title": "Top 10  namespace backlog (msgs)",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": " topk(10, sum(pulsar_msg_backlog{job=~\"broker\", kubernetes_namespace=~\"$kubernetes_namespace\"}) by (namespace))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Top 10  topics backlog (bytes)",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "expr": " topk(10, sum(pulsar_storage_backlog_size{job=~\"broker\", kubernetes_namespace=~\"$kubernetes_namespace\"}) by (namespace))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Throughput (bytes/s)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_throughput_in{job=~\"broker\"}) by (cluster)",
     "legendFormat": "{{ cluster }} - In"
    },
    {
     "expr": "sum(pulsar_throughput_out{job=~\"broker\"}) by (cluster)",
     "legendFormat": "{{ cluster }} - Out"
    }
   ]
  },
  {
   "title": "Storage Write Latency",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "msg / s" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_storage_write_latency_le_0_5{job=~\"broker\", kubernetes_namespace=~\"$kubernetes_namespace\"}) / 60.0",
     "legendFormat": "0 - 0.5 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_1{job=~\"broker\", kubernetes_namespace=~\"$kubernetes_namespace\"}) / 60.0",
     "legendFormat": "0.5 - 1 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_5{job=~\"broker\", kubernetes_namespace=~\"$kubernetes_namespace\"}) / 60.0",
     "legendFormat": "1 - 5 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_10{job=~\"broker\", kubernetes_namespace=~\"$kubernetes_namespace\"}) / 60.0",
     "legendFormat": "5 - 10 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_20{job=~\"broker\", kubernetes_namespace=~\"$kubernetes_namespace\"}) / 60.0",
     "legendFormat": "10 - 20 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_50{job=~\"broker\", kubernetes_namespace=~\"$kubernetes_namespace\"}) / 60.0",
     "legendFormat": "20 - 50 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_100{job=~\"broker\", kubernetes_namespace=~\"$kubernetes_namespace\"}) / 60.0",
     "legendFormat": "50 - 100 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_200{job=~\"broker\", kubernetes_namespace=~\"$kubernetes_namespace\"}) / 60.0",
     "legendFormat": "100 - 200 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_1000{job=~\"broker\", kubernetes_namespace=~\"$kubernetes_namespace\"}) / 60.0",
     "legendFormat": "200 ms - 1 s"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_overflow{job=~\"broker\", kubernetes_namespace=~\"$kubernetes_namespace\"}) / 60.0",
     "legendFormat": "> 1 s"
    }
   ]
  },
  {
   "title": "Top 10  topics backlog (bytes)",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": " topk(10, sum(pulsar_storage_backlog_size{job=~\"broker\", kubernetes_namespace=~\"$kubernetes_namespace\"}) by (topic))",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  {
   "title": "Top 10  topics backlog (messages)",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "expr": " topk(10, sum(pulsar_msg_backlog{job=~\"broker\", kubernetes_namespace=~\"$kubernetes_namespace\"}) by (topic))",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node CPU usage",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 * (1 - (sum(increase(node_cpu_seconds_total{mode=\"idle\"}[1m])) by (kubernetes_pod_name)\n/ \nsum(increase(node_cpu_seconds_total[1m])) by (kubernetes_pod_name)))",
       "legendFormat": "{{ kubernetes_pod_name }}"
      }
     ]
    },
    {
     "title": "Node Memory Usage",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes) / node_memory_MemTotal_bytes * 100 ",
       "legendFormat": "{{ kubernetes_pod_name }}"
      }
     ]
    }
   ]
  }
 ]
}