{
 "title": "Pulsar / Topic Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "pulsar_storage_size{cluster=~\".+\"}"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "pulsar_storage_size{namespace=~\".+\"}"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "pulsar_storage_size{topic=~\".+\"}"
    }
   },
   {
    "name": "kubernetes_namespace",
    "query": {
     "query": "pulsar_storage_size{kubernetes_namespace=~\".+\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Local publish rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "msg/s" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_rate_in{cluster=~\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\", kubernetes_namespace=~\"$kubernetes_namespace\"}) by (cluster, namespace, topic)",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  {
   "title": "Local delivery rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "msg / s" }
   ],
   "targets": [
    {
     "expr": "sum(  pulsar_subscription_msg_rate_out{      cluster=~\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\", kubernetes_namespace=~\"$kubernetes_namespace\"  }) by (cluster, namespace, topic, subscription)",
     "legendFormat": "{{ topic }} - {{subscription}}"
    }
   ]
  },
  {
   "title": "Local publish throughput (bytes/s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_throughput_in{cluster=~\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\", kubernetes_namespace=~\"$kubernetes_namespace\"}) by (cluster, namespace, topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Local delivery throughput (bytes/s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(  pulsar_subscription_msg_throughput_out{    cluster=~\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\", kubernetes_namespace=~\"$kubernetes_namespace\"  }) by (cluster, namespace, topic, subscription)",
     "legendFormat": "{{ topic }} - {{subscription}}"
    }
   ]
  },
  {
   "title": "Topics - Producers - Subscriptions - Consumers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_producers_count{cluster=~\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\", kubernetes_namespace=~\"$kubernetes_namespace\"})",
     "legendFormat": "producers"
    },
    {
     "expr": "sum(pulsar_subscriptions_count{cluster=~\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\", kubernetes_namespace=~\"$kubernetes_namespace\"})",
     "legendFormat": "subscriptions"
    },
    {
     "expr": "sum(pulsar_consumers_count{cluster=~\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\", kubernetes_namespace=~\"$kubernetes_namespace\"})",
     "legendFormat": "consumers"
    }
   ]
  },
  {
   "title": "Local backlog",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Messages" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_subscription_back_log{cluster=~\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\", kubernetes_namespace=~\"$kubernetes_namespace\"}) by (cluster, namespace, topic, subscription)",
     "legendFormat": "{{ topic }} - {{subscription}}"
    }
   ]
  },
  {
   "title": "Delayed Messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Messages" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_subscription_delayed{cluster=~\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\", kubernetes_namespace=~\"$kubernetes_namespace\"}) by (cluster, namespace, topic, subscription)",
     "legendFormat": "{{ topic }} - {{subscription}}"
    }
   ]
  },
  {
   "title": "Backlog Storage Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "decbytes", "label": "count" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_storage_backlog_size{cluster=~\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\", kubernetes_namespace=~\"$kubernetes_namespace\"}) by (cluster, namespace, topic)",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  {
   "title": "Backlog Quota Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "percent", "label": "count" }
   ],
   "targets": [
    {
     "expr": "100*sum(pulsar_storage_backlog_size{cluster=~\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\", kubernetes_namespace=~\"$kubernetes_namespace\"}) by (cluster, namespace, topic)/sum(pulsar_storage_backlog_quota_limit{cluster=~\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\", kubernetes_namespace=~\"$kubernetes_namespace\"}) by (cluster, namespace, topic)",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  {
   "title": "2nd Tier Storage Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_storage_offloaded_size{cluster=~\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\", kubernetes_namespace=~\"$kubernetes_namespace\"}) by (cluster, namespace, topic)",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  {
   "title": "Incoming replication rate | any → $cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_replication_rate_in{cluster=~\"$cluster\", namespace=~\"$namespace\", remote_cluster!=\"local\", topic=~\"$topic\", kubernetes_namespace=~\"$kubernetes_namespace\"}) by (cluster, remote_cluster)",
     "legendFormat": "{{remote_cluster}} → {{cluster}}"
    }
   ]
  },
  {
   "title": "Outgoing replication rate | $cluster → any",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_replication_rate_out{cluster=~\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\", kubernetes_namespace=~\"$kubernetes_namespace\"})",
     "legendFormat": "{{cluster}} → {{remote_cluster}}"
    }
   ]
  },
  {
   "title": "Replication backlog | $cluster → any",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_replication_backlog{cluster=~\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\", kubernetes_namespace=~\"$kubernetes_namespace\"}) by (cluster, remote_cluster)",
     "legendFormat": "{{cluster}} → {{remote_cluster}}"
    }
   ]
  },
  {
   "title": "Storage Write Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "msg / s" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_storage_write_latency_le_0_5{cluster=~\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\", kubernetes_namespace=~\"$kubernetes_namespace\"}) / 60.0",
     "legendFormat": "0 - 0.5 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_1{cluster=~\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\", kubernetes_namespace=~\"$kubernetes_namespace\"}) / 60.0",
     "legendFormat": "0.5 - 1 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_5{cluster=~\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\", kubernetes_namespace=~\"$kubernetes_namespace\"}) / 60.0",
     "legendFormat": "1 - 5 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_10{cluster=~\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\", kubernetes_namespace=~\"$kubernetes_namespace\"}) / 60.0",
     "legendFormat": "5 - 10 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_20{cluster=~\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\", kubernetes_namespace=~\"$kubernetes_namespace\"}) / 60.0",
     "legendFormat": "10 - 20 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_50{cluster=~\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\", kubernetes_namespace=~\"$kubernetes_namespace\"}) / 60.0",
     "legendFormat": "20 - 50 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_100{cluster=~\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\", kubernetes_namespace=~\"$kubernetes_namespace\"}) / 60.0",
     "legendFormat": "50 - 100 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_200{cluster=~\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\", kubernetes_namespace=~\"$kubernetes_namespace\"}) / 60.0",
     "legendFormat": "100 - 200 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_1000{cluster=~\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\", kubernetes_namespace=~\"$kubernetes_namespace\"}) / 60.0",
     "legendFormat": "200 ms - 1 s"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_overflow{cluster=~\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\", kubernetes_namespace=~\"$kubernetes_namespace\"}) / 60.0",
     "legendFormat": "> 1 s"
    }
   ]
  },
  {
   "title": "Storage entry size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "msg / s" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_entry_size_le_128{cluster=~\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\", kubernetes_namespace=~\"$kubernetes_namespace\"}) / 60.0",
     "legendFormat": "< 128 bytes"
    },
    {
     "expr": "sum(pulsar_entry_size_le_512{cluster=~\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\", kubernetes_namespace=~\"$kubernetes_namespace\"}) / 60.0",
     "legendFormat": "< 512 bytes"
    },
    {
     "expr": "sum(pulsar_entry_size_le_1_kb{cluster=~\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\", kubernetes_namespace=~\"$kubernetes_namespace\"}) / 60.0",
     "legendFormat": "< 1 KB"
    },
    {
     "expr": "sum(pulsar_entry_size_le_2_kb{cluster=~\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\", kubernetes_namespace=~\"$kubernetes_namespace\"}) / 60.0",
     "legendFormat": "< 2 KB"
    },
    {
     "expr": "sum(pulsar_entry_size_le_4_kb{cluster=~\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\", kubernetes_namespace=~\"$kubernetes_namespace\"}) / 60.0",
     "legendFormat": "< 4 KB"
    },
    {
     "expr": "sum(pulsar_entry_size_le_16_kb{cluster=~\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\", kubernetes_namespace=~\"$kubernetes_namespace\"}) / 60.0",
     "legendFormat": "< 16 KB"
    },
    {
     "expr": "sum(pulsar_entry_size_le_100_kb{cluster=~\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\", kubernetes_namespace=~\"$kubernetes_namespace\"}) / 60.0",
     "legendFormat": "< 100 KB"
    },
    {
     "expr": "sum(pulsar_entry_size_le_1_mb{cluster=~\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\", kubernetes_namespace=~\"$kubernetes_namespace\"}) / 60.0",
     "legendFormat": "< 1 MB"
    },
    {
     "expr": "sum(pulsar_entry_size_overflow{cluster=~\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\", kubernetes_namespace=~\"$kubernetes_namespace\"}) / 60.0",
     "legendFormat": "> 1 MB"
    }
   ]
  },
  {
   "title": "Storage Write Rate",
   "type": "graph",
   "description": "Rate of writes into storage (can be lower than publish rate, when batching is enabled)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_storage_write_rate{cluster=~\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\", kubernetes_namespace=~\"$kubernetes_namespace\"})",
     "legendFormat": "{{ topic }} "
    }
   ]
  },
  {
   "title": "Storage read entry rate",
   "type": "graph",
   "description": "Reads from bookies",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_storage_read_rate{cluster=~\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\", kubernetes_namespace=~\"$kubernetes_namespace\"})",
     "legendFormat": "{{ topic }} "
    }
   ]
  }
 ]
}